apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: aquarius
  name: aquarius
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: aquarius
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: aquarius
    spec:
      containers:
      - env:
        - name: LOG_LEVEL
          value: DEBUG
        - name: AQUARIUS_BIND_URL
          value: http://0.0.0.0:5000
        - name: AQUARIUS_WORKERS
          value: "2"
        - name: DB_HOSTNAME
          value: elasticsearch-master
        - name: DB_MODULE
          value: elasticsearch
        - name: DB_NAME
          value: aquarius
        - name: DB_PORT
          value: "9200"
        - name: DB_SCHEME
          value: http
        # - name: DB_USERNAME
        #   value: elastic
        # - name: DB_PASSWORD
        #   value: changeme
        - name: DB_SSL
          value: "false"
        - name: RUN_AQUARIUS_SERVER
          value: "1"
        - name: RUN_EVENTS_MONITOR
          value: "1"
        - name: EVENTS_ALLOW
          value: "0"
        - name: CONFIG_FILE
          value: config.ini
        - name: EVENTS_RPC
          value: 'https://rinkeby.infura.io/v3/5b10c1d10f19480dbb33a6150242c125'
        - name: BFACTORY_BLOCK
          value: "7298806"
        - name: METADATA_CONTRACT_BLOCK
          value: "7298808"
        - name: NETWORK_NAME
          value: 'rinkeby'
        - name: OCEAN_ADDRESS
          value: 0x8967BCF84170c91B0d24D4302C2376283b0B3a07
        - name: BLOCKS_CHUNK_SIZE
          value: "5000"
        - name: EVENTS_HTTP
          value: '1'
        image: oceanprotocol/aquarius:latest
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 5000
            scheme: HTTP
          initialDelaySeconds: 20
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 2
        name: aquarius
        ports:
        - containerPort: 5000
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 5000
            scheme: HTTP
          initialDelaySeconds: 20
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 500m
            memory: 500Mi
          requests:
            cpu: 500m
            memory: 500Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: aq-service-lb
spec:
  selector:
    app: aquarius
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: LoadBalancer

---
apiVersion: v1
kind: Service
metadata:
  name: aq-service-cip
spec:
  selector:
    app: aquarius
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5000
  type: ClusterIP